language: node_js
node_js:
  - 10
  - 11
  - 12
  - 13
  - 14
  - 15

script:
  - npm test
  - npm run build

cache: npm

after_success:
  - curl -T "{$(echo dist/*.* | tr ' ' ',')}" $FTP_SERVER --user $FTP_USER:$FTP_PASS
