language: node_js
node_js:
  # - 10
  # - 11
  # - 12
  # - 13
  # - 14
  - 15

script:
  - npm test
  - npm run build

cache: npm

after_success:
  # - ping $FTP_SERVER
  # - find dist/* -type f | xargs -L 1 bash -c 'curl -v --ftp-create-dirs -T  $1 -u $FTP_USER:$FTP_PASS ftp://$FTP_SERVER/${1##*/}' \;
  # - find *.mp3 -type f | xargs -L 1 bash -c 'curl -v --ftp-create-dirs -T  $1 -u $FTP_USER:$FTP_PASS ftp://$FTP_SERVER/${1##*/}' \;

branches:
  only:
    - master
